### PR TITLE
Testing setup improvements

### PR DESCRIPTION
**Pull request by ptrdom**
References https://github.com/tminglei/slick-pg/issues/515.

I though about two ways of implementing this - either having multiple sbt modules for each Postgres version, or just passing the Postgres version in environmental/vm variables. Latter option seemed to be easier to maintain - when new Postgres version comes out, only thing that will need to be added to CI will be a new value into the strategy matrix.

### CODE REVIEW

**Comment by ptrdom** [comment]
@tminglei I think you need to enable the GitHub Action workflow that I have added - https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow.

**Comment by tminglei** [comment]
Merged. Thanks! 👍

**Comment by ptrdom** [comment]
@tminglei Hmm, there seem to be issues with running the actions, this needs a closer look. We merged a bit early :) I will check it out.

**Comment by tminglei** [comment]
@ptrdom I resolved the issue.

**Comment by ptrdom** [comment]
> @ptrdom I resolved the issue.

Hmm, I would suggest to double check how env/vm argument for Postgres version is passed - currently CI in master runs only against 11. It should look something like https://github.com/ptrdom/slick-pg/blob/d760e470fecccb9d616434ebe75c8c2529d7e46e/.github/workflows/ci.yml#L19-L28.

**Comment by tminglei** [comment]
@ptrdom oh, yes, only postgres 11 was used. It seems SLICK_PG_TEST_POSTGRES_IMAGE_TAG not to be passed.

**Comment by tminglei** [comment]
@ptrdom applied your code to 851a614. It works! 👍

**Pull request merged**
