### PR TITLE
Added failing test case for a simple composite type

### PR DESCRIPTION
**Pull request by DylanMLG**
I'm not sure what the fix is but if you have any ideas what the problem is I would greatly appreciate any information as I'm trying to implement a feature that uses this at the moment.

It breaks in the slick-pg internals in an unescape method.

Thank you!

### CODE REVIEW

**Comment by tminglei** [comment]
Merged. I'll continue to fix it.

**Comment by tminglei** [comment]
Hi @DylanMLG, the fix was release in slick-pg v0.10.0-M2.
Pls check it.

**Comment by DylanArnold** [comment]
Thanks for the fix. I had quick look before I ran out of time but I think the original problem is fixed (another one pops up though) but I think it is related to the play framework classloader problems.

I'll try to verify it properly tomorrow, since I might need to create a test project.

(Just posting this on my other account).

**Comment by DylanMLG** [comment]
The original problem appears to be fixed. I'm trying to work through some classloader issues with play framework now.

After your fix I started getting some of the dreaded forName errors but I noticed you can now pass plays classloader to DatabaseConfig.forConfig

That fixed some issues but now I am getting an exception in `CompositeConverter` at the following call

```scala
rm.reflectClass(theType.typeSymbol.asClass).reflectConstructor(constructor)
          .apply(args: _*)
```

It's a java.lang.ClassNotFoundException path.to.my.MyCustomCompositeType

Do you have any idea what could cause that? Could it be a similar problem to slick-pg needing to use plays classloader?

**Comment by tminglei** [comment]
Not clear what happened in your side, since you didn't provide enough details.

But you defined `MyCustomCompositeType` inside a **class**, or outside a **class**?
_If it's inside a **class**, maybe you can try to move outside, like [PgCompositeSupportSuite](https://github.com/tminglei/slick-pg/blob/master/src/test/scala/com/github/tminglei/slickpg/PgCompositeSupportSuite.scala) did._

**Comment by DylanMLG** [comment]
@tminglei I found the problem. My type is defined outside a class.

It looks like it's a similar problem to the one that slick has with plays classloader. It can be solved in a similar way to https://github.com/slick/slick/pull/1152

See commit https://github.com/jroper/slick/commit/1abf7539d3efa97103c770d82fc725c134960f3c

I fixed the problem (quick and dirty) by passing plays classloader to PgCompositeSupportUtils and using that in the reflect calls.

See this commit https://github.com/DylanMLG/slick-pg/commit/afe7eaa7451800f84b47509a4bbd153835b27f17

The diff is unfortunately not useful but note the following:

```scala
  var _classLoader: Option[ClassLoader] = None

  def setClassLoader(classLoader: ClassLoader) = _classLoader = Some(classLoader)

  def classLoader = _classLoader.getOrElse(getClass.getClassLoader)
```

```scala
u.runtimeMirror(classLoader).reflectClass(theType.typeSymbol.asClass).reflectConstructor(constructor)
          .apply(args: _*)
```

```scala
val instanceMirror = u.runtimeMirror(classLoader).reflect(value)
```

It would be very useful to get something like this into slick-pg

**Comment by tminglei** [comment]
Yeah, but we need to find a more convenient way.

**Comment by DylanMLG** [comment]
I agree. I'm not really sure what it is though.

**Comment by tminglei** [comment]
Hi @DylanMLG, I made some enhancement in branch [cl](https://github.com/tminglei/slick-pg/tree/cl), but I haven't a good case to test it.
Can you help check it?

**Comment by DylanMLG** [comment]
@tminglei The cl branch works perfectly.

It's interesting. I didn't even need to explicitly pass the play class loader. Just the default getClass.getClassLoader returns the PlayDependencyClassLoader and everything works.

Thank you for all your hard work :)

**Comment by tminglei** [comment]
Sounds good! _**:-)**_
Then I'll merge it into master branch.

_Thanks! :+1:_

**Comment by hvesalai** [comment]
Guys this is not cool 

`for(i <- (-1 + step) to (value.length, step) if i < value.length) yield value.charAt(i)`

It should be

`for(i <- (-1 + step) until (value.length, step)) yield value.charAt(i)`

I.e. instead of using the guard, you should change `to` to `until`

**Comment by tminglei** [comment]
Yes, thanks for pointing it out. _:+1:_

**Pull request merged**
