### PR TITLE
upgrade slick to 3.1.0-RC1

### PR DESCRIPTION
**Pull request by TimothyKlim**

### CODE REVIEW

**Comment by tminglei** [comment]
Merged. _Thanks! :+1:_

**Comment by TimothyKlim** [comment]
Thank you! 👍

**Comment by tminglei** [comment]
Hi @TimothyKlim, just released slick-pg v0.10.0-RC1, you can help check it.
_Cheers! ^^_

**Comment by TimothyKlim** [comment]
Hi @tminglei, for my current project its works as always good! 👌

**Pull request merged**
