### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by TimothyKlim**

### CODE REVIEW

**Comment by tminglei** [comment]
Merged. _Thanks! :+1:_

**Comment by pettyjamesm** [comment]
Is M5 going to be published anytime soon? Also, should this be considered "stable" against slick-3.2.0 and ready for use?

**Comment by tminglei** [comment]
I tried but failed. The maven central was blocked by the Government.

**Comment by pettyjamesm** [comment]
Sorry to hear that. Is this likely to be a temporary or permanent issue?

**Comment by tminglei** [comment]
Temporary. But I don't know how long it will continue.

**Pull request merged**
