### PR TITLE
Try slick 3.4.0-M1

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by nafg** [comment]
How do you want to go about this? Would you publish a prerelease? Would you do so from the master branch? (That might interfere with your ability to release other updates meanwhile)

**Comment by tminglei** [comment]
Merged. Thanks! 👍

**Comment by nafg** [comment]
Umm I guess that answers my question. Did you just do that or is it automated?

**Comment by tminglei** [comment]
Yes, I just did that.

**Pull request merged**
